### ISSUE TITLE
error: package com.i18nstorage does not exist

### ISSUE THREAD

**Issue by AHMED-5G** [ahmedrowaihi/react-native-i18n-storage#5] opened 2023-05-09 18:39 UTC
React Native 0.71.7 

import com.i18nstorage.I18nStorageUtility;

error: package com.i18nstorage does not exist

![Screenshot from 2023-05-09 21-38-23](https://github.com/ahmedrowaihi/react-native-i18n-storage/assets/75797110/11ad78c0-b3de-4239-9f45-1dee75964a9c)

**Comment by ahmedrowaihi** [comment] 2023-05-10 18:06
Hey @AHMED-5G !
Thank you for issuing this, I will not be able to maintain this month due to my final exams.
would be happy for any contributions.

**Comment by ahmedrowaihi** [comment] 2023-05-11 05:33
@AHMED-5G 
please make sure you followed the instructions in the [prerequisites](https://github.com/ahmedrowaihi/react-native-i18n-storage#prerequisites), install the [@react-native-async-storage/async-storage](@react-native-async-storage/async-storage) so gradle will include this dependence, also use the appropriate version of [react-native-restart](https://www.npmjs.com/package/react-native-restart) which should be `npm install react-native-restart@0.0.27` for `RN >= 0.71` as it's stated here [react-native-restart#installation](https://github.com/avishayil/react-native-restart#installation).

let me know if the problem is not solved after installing

**Comment by AHMED-5G** [comment] 2023-05-11 05:38
> let me know if the problem is not solved after installing

Tried again maybe attached error cause this now looks nice 
![Screenshot from 2023-05-11 08-28-59](https://github.com/ahmedrowaihi/react-native-i18n-storage/assets/75797110/0af33912-c5e6-49e3-aac5-1c3029e51c25)


![Screenshot_1683783189](https://github.com/ahmedrowaihi/react-native-i18n-storage/assets/75797110/be9a8ccf-07c3-4105-884e-84c12e086e1c)


![Screenshot_1683783181](https://github.com/ahmedrowaihi/react-native-i18n-storage/assets/75797110/f22c09de-e7a9-44b2-9b83-b1b92a2f2580)

**Comment by ahmedrowaihi** [comment] 2023-05-11 05:43
Here is a repo example I just made for you with `RN >= 0.71`,

- clean gradle build
1. `cd android` -> `gradlew clean`
2. `npm run android` to rebuild the app and run.


use this as a reference 
[AwesomeProject-with-i18n-Storage](https://github.com/ahmedrowaihi/AwesomeProject-with-i18n-Storage)

# Note: Expo Go is not supported

**Comment by ahmedrowaihi** [comment] 2023-05-11 05:52
> 
> Tried again maybe attached error cause this now looks nice ![Screenshot from 2023-05-11 08-28-59](https://user-images.githubusercontent.com/75797110/237583086-0af33912-c5e6-49e3-aac5-1c3029e51c25.png)
> 


### I noticed the Error message is from an old version of this `react-native-i18n-storage`, make sure you installed the latest version `2.0.5` 

### `npm install @ahmedrowaihi/react-native-i18n-storage@2.0.5`

**Comment by ahmedrowaihi** [comment] 2023-05-11 07:48
@AHMED-5G let me know if I can close this issue & all are good.

**Comment by AHMED-5G** [comment] 2023-05-11 13:27
> @AHMED-5G let me know if I can close this issue & all are good.

 All are good, thank you

**Closed as completed** 2023-05-11 13:30 UTC
